### PR TITLE
Add changes to work better with pytorch-grad-cam

### LINKED ISSUE #45: Support for GradCam
Look into the possibility of using [pytorch-grad-cam](https://github.com/jacobgil/pytorch-grad-cam) with bioclip. As part of this we would need to gather feedback on the caveats related using GradCam with pybioclip.

### PR DESCRIPTION
**Pull request by johnbradley**
Changes classifier base class to extend nn.Module and implements the forward() method so the classifiers can be used with pytorch-grad-cam. torch.no_grad was removed from create_probabilities because the calling functions already did this and pytorch-grad-cam needs grad enabled.

Fixes #45

### CODE REVIEW

**Comment by johnbradley** [comment]
@Link7808 FYI on this PR.

**Comment by johnbradley** [comment]
The COLAB URL in the README points to a file that doesn't exist until this is merged. Also you will need to install pybioclip from this branch as well.
To test the notebook on COLAB use this link: https://colab.research.google.com/github/Imageomics/pybioclip/blob/gradcam/examples/GradCamExperiment.ipynb
Change the installation cell to this value:
```
!pip install -q git+https://github.com/imageomics/pybioclip.git@gradcam grad-cam
```

**Review by hlapp — APPROVED** [review]
Looks great to me!

**Review by egrace479 — APPROVED** [review]

**Comment by johnbradley** [comment]
I merged in the main branch and moved the new notebook link from the README to the python-tutorial.md.

**Pull request merged**
