### PR TITLE
Predict from list of PIL images in CustomLabelsClassifier

### PR DESCRIPTION
**Pull request by yanis-falaki**
Added function predict_from_list_pil() on line 209 in predict.py. Allows the ability to get predictions from a list of pil images and class labels. The function can either return the raw probabilities tensor (which is useful for some work I'm doing), or a list of formatted objects similar to the predict function.

### CODE REVIEW

**Comment by johnbradley** [comment]
Thanks for this PR @yanis-falaki! I have some similar changes in the works for both the CustomLabelsClassifier and TreeOfLifeClassifier. Once that is finished I'll circle back around to this PR.

I noticed your function has a `return_formatted` boolean parameter. In your work are you using both True and False for this parameter?

**Comment by yanis-falaki** [comment]
@johnbradley Hey, for the `return_formatted` parameter I only ever make use of the False value, but made the option for it to be returned in a format consistent with the other predict function.

**Comment by johnbradley** [comment]
@yanis-falaki Changes to process multiple images at once has been merged into the main branch.
Please consider reworking your PR to take advantage of these changes.

Given the following setup:
```
from bioclip import CustomLabelsClassifier
import PIL.Image
cls_ary = ["duck","fish","bear"]
paths = ["Ursus-arctos.jpeg", "Amanita-muscaria.jpeg"]
images = [PIL.Image.open(path).convert("RGB") for path in paths]
```
You should be able to do something like this to calculate the probabilities:
```
classifier = CustomLabelsClassifier(cls_ary)
img_features = classifier.create_image_features(images)
probs = classifier.create_probabilities(img_features, classifier.txt_features)
```

The images above are from the [bioclip-demo](https://huggingface.co/spaces/imageomics/bioclip-demo/tree/main/examples).

**Comment by hlapp** [comment]
I think this functionality has now been incorporated into the main branch, so I'm going to close this out. But anyone can reopen if some piece is missing.

**Pull request closed without merging**
