### PR TITLE
Adds Dockerfile + release container building

### PR DESCRIPTION
**Pull request by johnbradley**
Command to build the container for pybioclip:
```
docker build --platform=linux/amd64 --build-arg="PYBIOCLIP_VERSION=1.0.0" -t pybioclip .
```

Adds GitHub action config to build the docker container on release.

### CODE REVIEW

**Comment by johnbradley** [comment]
I plan on creating a subsequent issue/PR with to update the README. I have quite a few notes for Docker but the README is already rather long. My plan for that future work is to move the details out into the wiki and link to it from the README.

**Comment by johnbradley** [comment]
I tested and you can push an apptainer image to ghcr.io. However it will replace any existing docker. The GitHub UI also is wrong after pushing an apptainer(oras) image telling users to use docker to pull/run.

**Review by hlapp — APPROVED** [review]
🎉👍

**Review by egrace479 — APPROVED** [review]
🚀

**Pull request merged**
