### PR TITLE
Add device parameter and examples

### PR DESCRIPTION
**Pull request by johnbradley**
Adds `--device=<device>` command line parameter to use cpu, cuda, or mps.
Adds some example notebooks.

### CODE REVIEW

**Comment by johnbradley** [comment]
The colab badges in README do not work because the branch name is main.
Here are badges with the cuda branch:

Predict species for images<a target="_blank" href="https://colab.research.google.com/github/Imageomics/pybioclip/blob/cuda/examples/PredictImages.ipynb">
  Open In Colab</a>

Predict species for [iNaturalist](https://www.inaturalist.org/) images<a target="_blank" href="https://colab.research.google.com/github/Imageomics/pybioclip/blob/cuda/examples/iNaturalistPredict.ipynb">
  Open In Colab

**Comment by egrace479** [comment]
Sample notebooks are great, and very helpful to choose device! 

One question. When I run them in Colab I get warnings about not having a saved HF Token and the following `Runtime Warning` at the "Predictions" and "Make Predictions" steps. We could add a note about the HF Token, but I think it'd be more confusing since it's not needed for public repos. Neither of these errors occur when I run the notebooks locally on my machine, so I'm wondering if the runtime warning has to do with the `python` version or is otherwise specific to Colab: I'm running 3.11.9 locally, but Colab seems to have 3.10.

> /usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()

**Comment by johnbradley** [comment]
Thanks @egrace479 .

These warnings occur here when I run the notebook in COLAB:
Screenshot 2024-05-07 at 6 44 13 AM

These warnings look to be related to downloading the model files.
The HF_TOKEN warning comes from [huggingface_hub COLAB specific code](https://github.com/huggingface/huggingface_hub/blob/5ff2d150d121d04799b78bc08f2343c21b8f07a9/src/huggingface_hub/utils/_token.py#L89-L95).

The JAX os.fork warning comes from [jax](https://github.com/google/jax/blob/3e5a18f1e234ce5a6daa026786ce2854980cf451/jax/_src/xla_bridge.py#L129-L132).


----

Even with accessing a public model setting your HF_TOKEN is probably a good suggestion. It would likely avoid some rate limiting errors.

I think the JAX fork warning is a red herring. From what I have read jax is incompatbile with fork so you can't use parallel processing and jax. It looks like loading jax causes this warning to be set in os.fork. I assume the HF code is just downloading files using parallel processing to speed that up. This [pytorch issue](https://github.com/pytorch/pytorch/issues/123954) sounds like future version of pytorch will fix this.

I'll add a note to the markdown cell above this code in the notebooks.

**Comment by johnbradley** [comment]
For the note how does sound:

## Predict species
NOTE: You may see warnings `The secret 'HF_TOKEN' does not exist in your Colab secrets.` and `RuntimeWarning: os.fork()` when running the code block below. Consider setting the HF_TOKEN environment variable to avoid rate limiting errors when running in COLAB. The `os.fork()` warning appears to be a false positive related to [this pytorch issue](https://github.com/pytorch/pytorch/issues/123954).

**Comment by egrace479** [comment]
> For the note how does sound:
> 
> ## Predict species
> NOTE: You may see warnings `The secret 'HF_TOKEN' does not exist in your Colab secrets.` and `RuntimeWarning: os.fork()` when running the code block below. Consider setting the HF_TOKEN environment variable to avoid rate limiting errors when running in COLAB. The `os.fork()` warning appears to be a false positive related to [this pytorch issue](https://github.com/pytorch/pytorch/issues/123954).

That seems reasonable.

**Review by hlapp — APPROVED** [review]
👍

**Review by egrace479 — APPROVED** [review]

**Pull request merged**
